<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        City::create(["id"=>"1101", "province_id"=>"11", "city_code"=> "1101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIMEULUE", "name"=>"SIMEULUE"]);
        City::create(["id"=>"1102", "province_id"=>"11", "city_code"=> "1102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH SINGKIL", "name"=>"ACEH SINGKIL"]);
        City::create(["id"=>"1103", "province_id"=>"11", "city_code"=> "1103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH SELATAN", "name"=>"ACEH SELATAN"]);
        City::create(["id"=>"1104", "province_id"=>"11", "city_code"=> "1104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH TENGGARA", "name"=>"ACEH TENGGARA"]);
        City::create(["id"=>"1105", "province_id"=>"11", "city_code"=> "1105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH TIMUR", "name"=>"ACEH TIMUR"]);
        City::create(["id"=>"1106", "province_id"=>"11", "city_code"=> "1106", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH TENGAH", "name"=>"ACEH TENGAH"]);
        City::create(["id"=>"1107", "province_id"=>"11", "city_code"=> "1107", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH BARAT", "name"=>"ACEH BARAT"]);
        City::create(["id"=>"1108", "province_id"=>"11", "city_code"=> "1108", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH BESAR", "name"=>"ACEH BESAR"]);
        City::create(["id"=>"1109", "province_id"=>"11", "city_code"=> "1109", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PIDIE", "name"=>"PIDIE"]);
        City::create(["id"=>"1110", "province_id"=>"11", "city_code"=> "1110", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BIREUEN", "name"=>"BIREUEN"]);
        City::create(["id"=>"1111", "province_id"=>"11", "city_code"=> "1111", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH UTARA", "name"=>"ACEH UTARA"]);
        City::create(["id"=>"1112", "province_id"=>"11", "city_code"=> "1112", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH BARAT DAYA", "name"=>"ACEH BARAT DAYA"]);
        City::create(["id"=>"1113", "province_id"=>"11", "city_code"=> "1113", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GAYO LUES", "name"=>"GAYO LUES"]);
        City::create(["id"=>"1114", "province_id"=>"11", "city_code"=> "1114", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH TAMIANG", "name"=>"ACEH TAMIANG"]);
        City::create(["id"=>"1115", "province_id"=>"11", "city_code"=> "1115", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NAGAN RAYA", "name"=>"NAGAN RAYA"]);
        City::create(["id"=>"1116", "province_id"=>"11", "city_code"=> "1116", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ACEH JAYA", "name"=>"ACEH JAYA"]);
        City::create(["id"=>"1117", "province_id"=>"11", "city_code"=> "1117", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BENER MERIAH", "name"=>"BENER MERIAH"]);
        City::create(["id"=>"1118", "province_id"=>"11", "city_code"=> "1118", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PIDIE JAYA", "name"=>"PIDIE JAYA"]);
        City::create(["id"=>"1171", "province_id"=>"11", "city_code"=> "1171", "jenis" => "KOTA", "name_lengkap" => "KOTA BANDA ACEH", "name"=>"BANDA ACEH"]);
        City::create(["id"=>"1172", "province_id"=>"11", "city_code"=> "1172", "jenis" => "KOTA", "name_lengkap" => "KOTA SABANG", "name"=>"SABANG"]);
        City::create(["id"=>"1173", "province_id"=>"11", "city_code"=> "1173", "jenis" => "KOTA", "name_lengkap" => "KOTA LANGSA", "name"=>"LANGSA"]);
        City::create(["id"=>"1174", "province_id"=>"11", "city_code"=> "1174", "jenis" => "KOTA", "name_lengkap" => "KOTA LHOKSEUMAWE", "name"=>"LHOKSEUMAWE"]);
        City::create(["id"=>"1175", "province_id"=>"11", "city_code"=> "1175", "jenis" => "KOTA", "name_lengkap" => "KOTA SUBULUSSALAM", "name"=>"SUBULUSSALAM"]);
        City::create(["id"=>"1201", "province_id"=>"12", "city_code"=> "1201", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NIAS", "name"=>"NIAS"]);
        City::create(["id"=>"1202", "province_id"=>"12", "city_code"=> "1202", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MANDAILING NATAL", "name"=>"MANDAILING NATAL"]);
        City::create(["id"=>"1203", "province_id"=>"12", "city_code"=> "1203", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TAPANULI SELATAN", "name"=>"TAPANULI SELATAN"]);
        City::create(["id"=>"1204", "province_id"=>"12", "city_code"=> "1204", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TAPANULI TENGAH", "name"=>"TAPANULI TENGAH"]);
        City::create(["id"=>"1205", "province_id"=>"12", "city_code"=> "1205", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TAPANULI UTARA", "name"=>"TAPANULI UTARA"]);
        City::create(["id"=>"1206", "province_id"=>"12", "city_code"=> "1206", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TOBA SAMOSIR", "name"=>"TOBA SAMOSIR"]);
        City::create(["id"=>"1207", "province_id"=>"12", "city_code"=> "1207", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LABUHAN BATU", "name"=>"LABUHAN BATU"]);
        City::create(["id"=>"1208", "province_id"=>"12", "city_code"=> "1208", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ASAHAN", "name"=>"ASAHAN"]);
        City::create(["id"=>"1209", "province_id"=>"12", "city_code"=> "1209", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIMALUNGUN", "name"=>"SIMALUNGUN"]);
        City::create(["id"=>"1210", "province_id"=>"12", "city_code"=> "1210", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DAIRI", "name"=>"DAIRI"]);
        City::create(["id"=>"1211", "province_id"=>"12", "city_code"=> "1211", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KARO", "name"=>"KARO"]);
        City::create(["id"=>"1212", "province_id"=>"12", "city_code"=> "1212", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DELI SERDANG", "name"=>"DELI SERDANG"]);
        City::create(["id"=>"1213", "province_id"=>"12", "city_code"=> "1213", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LANGKAT", "name"=>"LANGKAT"]);
        City::create(["id"=>"1214", "province_id"=>"12", "city_code"=> "1214", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NIAS SELATAN", "name"=>"NIAS SELATAN"]);
        City::create(["id"=>"1215", "province_id"=>"12", "city_code"=> "1215", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HUMBANG HASUNDUTAN", "name"=>"HUMBANG HASUNDUTAN"]);
        City::create(["id"=>"1216", "province_id"=>"12", "city_code"=> "1216", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PAKPAK BHARAT", "name"=>"PAKPAK BHARAT"]);
        City::create(["id"=>"1217", "province_id"=>"12", "city_code"=> "1217", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SAMOSIR", "name"=>"SAMOSIR"]);
        City::create(["id"=>"1218", "province_id"=>"12", "city_code"=> "1218", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SERDANG BEDAGAI", "name"=>"SERDANG BEDAGAI"]);
        City::create(["id"=>"1219", "province_id"=>"12", "city_code"=> "1219", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BATU BARA", "name"=>"BATU BARA"]);
        City::create(["id"=>"1220", "province_id"=>"12", "city_code"=> "1220", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PADANG LAWAS UTARA", "name"=>"PADANG LAWAS UTARA"]);
        City::create(["id"=>"1221", "province_id"=>"12", "city_code"=> "1221", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PADANG LAWAS", "name"=>"PADANG LAWAS"]);
        City::create(["id"=>"1222", "province_id"=>"12", "city_code"=> "1222", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LABUHAN BATU SELATAN", "name"=>"LABUHAN BATU SELATAN"]);
        City::create(["id"=>"1223", "province_id"=>"12", "city_code"=> "1223", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LABUHAN BATU UTARA", "name"=>"LABUHAN BATU UTARA"]);
        City::create(["id"=>"1224", "province_id"=>"12", "city_code"=> "1224", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NIAS UTARA", "name"=>"NIAS UTARA"]);
        City::create(["id"=>"1225", "province_id"=>"12", "city_code"=> "1225", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NIAS BARAT", "name"=>"NIAS BARAT"]);
        City::create(["id"=>"1271", "province_id"=>"12", "city_code"=> "1271", "jenis" => "KOTA", "name_lengkap" => "KOTA SIBOLGA", "name"=>"SIBOLGA"]);
        City::create(["id"=>"1272", "province_id"=>"12", "city_code"=> "1272", "jenis" => "KOTA", "name_lengkap" => "KOTA TANJUNG BALAI", "name"=>"TANJUNG BALAI"]);
        City::create(["id"=>"1273", "province_id"=>"12", "city_code"=> "1273", "jenis" => "KOTA", "name_lengkap" => "KOTA PEMATANG SIANTAR", "name"=>"PEMATANG SIANTAR"]);
        City::create(["id"=>"1274", "province_id"=>"12", "city_code"=> "1274", "jenis" => "KOTA", "name_lengkap" => "KOTA TEBING TINGGI", "name"=>"TEBING TINGGI"]);
        City::create(["id"=>"1275", "province_id"=>"12", "city_code"=> "1275", "jenis" => "KOTA", "name_lengkap" => "KOTA MEDAN", "name"=>"MEDAN"]);
        City::create(["id"=>"1276", "province_id"=>"12", "city_code"=> "1276", "jenis" => "KOTA", "name_lengkap" => "KOTA BINJAI", "name"=>"BINJAI"]);
        City::create(["id"=>"1277", "province_id"=>"12", "city_code"=> "1277", "jenis" => "KOTA", "name_lengkap" => "KOTA PADANGSIDIMPUAN", "name"=>"PADANGSIDIMPUAN"]);
        City::create(["id"=>"1278", "province_id"=>"12", "city_code"=> "1278", "jenis" => "KOTA", "name_lengkap" => "KOTA GUNUNGSITOLI", "name"=>"GUNUNGSITOLI"]);
        City::create(["id"=>"1301", "province_id"=>"13", "city_code"=> "1301", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN MENTAWAI", "name"=>"KEPULAUAN MENTAWAI"]);
        City::create(["id"=>"1302", "province_id"=>"13", "city_code"=> "1302", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PESISIR SELATAN", "name"=>"PESISIR SELATAN"]);
        City::create(["id"=>"1303", "province_id"=>"13", "city_code"=> "1303", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SOLOK", "name"=>"SOLOK"]);
        City::create(["id"=>"1304", "province_id"=>"13", "city_code"=> "1304", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIJUNJUNG", "name"=>"SIJUNJUNG"]);
        City::create(["id"=>"1305", "province_id"=>"13", "city_code"=> "1305", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANAH DATAR", "name"=>"TANAH DATAR"]);
        City::create(["id"=>"1306", "province_id"=>"13", "city_code"=> "1306", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PADANG PARIAMAN", "name"=>"PADANG PARIAMAN"]);
        City::create(["id"=>"1307", "province_id"=>"13", "city_code"=> "1307", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN AGAM", "name"=>"AGAM"]);
        City::create(["id"=>"1308", "province_id"=>"13", "city_code"=> "1308", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LIMA PULUH KOTA", "name"=>"LIMA PULUH KOTA"]);
        City::create(["id"=>"1309", "province_id"=>"13", "city_code"=> "1309", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PASAMAN", "name"=>"PASAMAN"]);
        City::create(["id"=>"1310", "province_id"=>"13", "city_code"=> "1310", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SOLOK SELATAN", "name"=>"SOLOK SELATAN"]);
        City::create(["id"=>"1311", "province_id"=>"13", "city_code"=> "1311", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DHARMASRAYA", "name"=>"DHARMASRAYA"]);
        City::create(["id"=>"1312", "province_id"=>"13", "city_code"=> "1312", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PASAMAN BARAT", "name"=>"PASAMAN BARAT"]);
        City::create(["id"=>"1371", "province_id"=>"13", "city_code"=> "1371", "jenis" => "KOTA", "name_lengkap" => "KOTA PADANG", "name"=>"PADANG"]);
        City::create(["id"=>"1372", "province_id"=>"13", "city_code"=> "1372", "jenis" => "KOTA", "name_lengkap" => "KOTA SOLOK", "name"=>"SOLOK"]);
        City::create(["id"=>"1373", "province_id"=>"13", "city_code"=> "1373", "jenis" => "KOTA", "name_lengkap" => "KOTA SAWAH LUNTO", "name"=>"SAWAH LUNTO"]);
        City::create(["id"=>"1374", "province_id"=>"13", "city_code"=> "1374", "jenis" => "KOTA", "name_lengkap" => "KOTA PADANG PANJANG", "name"=>"PADANG PANJANG"]);
        City::create(["id"=>"1375", "province_id"=>"13", "city_code"=> "1375", "jenis" => "KOTA", "name_lengkap" => "KOTA BUKITTINGGI", "name"=>"BUKITTINGGI"]);
        City::create(["id"=>"1376", "province_id"=>"13", "city_code"=> "1376", "jenis" => "KOTA", "name_lengkap" => "KOTA PAYAKUMBUH", "name"=>"PAYAKUMBUH"]);
        City::create(["id"=>"1377", "province_id"=>"13", "city_code"=> "1377", "jenis" => "KOTA", "name_lengkap" => "KOTA PARIAMAN", "name"=>"PARIAMAN"]);
        City::create(["id"=>"1401", "province_id"=>"14", "city_code"=> "1401", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUANTAN SINGINGI", "name"=>"KUANTAN SINGINGI"]);
        City::create(["id"=>"1402", "province_id"=>"14", "city_code"=> "1402", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN INDRAGIRI HULU", "name"=>"INDRAGIRI HULU"]);
        City::create(["id"=>"1403", "province_id"=>"14", "city_code"=> "1403", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN INDRAGIRI HILIR", "name"=>"INDRAGIRI HILIR"]);
        City::create(["id"=>"1404", "province_id"=>"14", "city_code"=> "1404", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PELALAWAN", "name"=>"PELALAWAN"]);
        City::create(["id"=>"1405", "province_id"=>"14", "city_code"=> "1405", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN S I A K", "name"=>"S I A K"]);
        City::create(["id"=>"1406", "province_id"=>"14", "city_code"=> "1406", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KAMPAR", "name"=>"KAMPAR"]);
        City::create(["id"=>"1407", "province_id"=>"14", "city_code"=> "1407", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ROKAN HULU", "name"=>"ROKAN HULU"]);
        City::create(["id"=>"1408", "province_id"=>"14", "city_code"=> "1408", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BENGKALIS", "name"=>"BENGKALIS"]);
        City::create(["id"=>"1409", "province_id"=>"14", "city_code"=> "1409", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ROKAN HILIR", "name"=>"ROKAN HILIR"]);
        City::create(["id"=>"1410", "province_id"=>"14", "city_code"=> "1410", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN MERANTI", "name"=>"KEPULAUAN MERANTI"]);
        City::create(["id"=>"1471", "province_id"=>"14", "city_code"=> "1471", "jenis" => "KOTA", "name_lengkap" => "KOTA PEKANBARU", "name"=>"PEKANBARU"]);
        City::create(["id"=>"1473", "province_id"=>"14", "city_code"=> "1473", "jenis" => "KOTA", "name_lengkap" => "KOTA D U M A I", "name"=>"D U M A I"]);
        City::create(["id"=>"1501", "province_id"=>"15", "city_code"=> "1501", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KERINCI", "name"=>"KERINCI"]);
        City::create(["id"=>"1502", "province_id"=>"15", "city_code"=> "1502", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MERANGIN", "name"=>"MERANGIN"]);
        City::create(["id"=>"1503", "province_id"=>"15", "city_code"=> "1503", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SAROLANGUN", "name"=>"SAROLANGUN"]);
        City::create(["id"=>"1504", "province_id"=>"15", "city_code"=> "1504", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BATANG HARI", "name"=>"BATANG HARI"]);
        City::create(["id"=>"1505", "province_id"=>"15", "city_code"=> "1505", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUARO JAMBI", "name"=>"MUARO JAMBI"]);
        City::create(["id"=>"1506", "province_id"=>"15", "city_code"=> "1506", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANJUNG JABUNG TIMUR", "name"=>"TANJUNG JABUNG TIMUR"]);
        City::create(["id"=>"1507", "province_id"=>"15", "city_code"=> "1507", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANJUNG JABUNG BARAT", "name"=>"TANJUNG JABUNG BARAT"]);
        City::create(["id"=>"1508", "province_id"=>"15", "city_code"=> "1508", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TEBO", "name"=>"TEBO"]);
        City::create(["id"=>"1509", "province_id"=>"15", "city_code"=> "1509", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BUNGO", "name"=>"BUNGO"]);
        City::create(["id"=>"1571", "province_id"=>"15", "city_code"=> "1571", "jenis" => "KOTA", "name_lengkap" => "KOTA JAMBI", "name"=>"JAMBI"]);
        City::create(["id"=>"1572", "province_id"=>"15", "city_code"=> "1572", "jenis" => "KOTA", "name_lengkap" => "KOTA SUNGAI PENUH", "name"=>"SUNGAI PENUH"]);
        City::create(["id"=>"1601", "province_id"=>"16", "city_code"=> "1601", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN OGAN KOMERING ULU", "name"=>"OGAN KOMERING ULU"]);
        City::create(["id"=>"1602", "province_id"=>"16", "city_code"=> "1602", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN OGAN KOMERING ILIR", "name"=>"OGAN KOMERING ILIR"]);
        City::create(["id"=>"1603", "province_id"=>"16", "city_code"=> "1603", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUARA ENIM", "name"=>"MUARA ENIM"]);
        City::create(["id"=>"1604", "province_id"=>"16", "city_code"=> "1604", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAHAT", "name"=>"LAHAT"]);
        City::create(["id"=>"1605", "province_id"=>"16", "city_code"=> "1605", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUSI RAWAS", "name"=>"MUSI RAWAS"]);
        City::create(["id"=>"1606", "province_id"=>"16", "city_code"=> "1606", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUSI BANYUASIN", "name"=>"MUSI BANYUASIN"]);
        City::create(["id"=>"1607", "province_id"=>"16", "city_code"=> "1607", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANYU ASIN", "name"=>"BANYU ASIN"]);
        City::create(["id"=>"1608", "province_id"=>"16", "city_code"=> "1608", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN OGAN KOMERING ULU SELATAN", "name"=>"OGAN KOMERING ULU SELATAN"]);
        City::create(["id"=>"1609", "province_id"=>"16", "city_code"=> "1609", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN OGAN KOMERING ULU TIMUR", "name"=>"OGAN KOMERING ULU TIMUR"]);
        City::create(["id"=>"1610", "province_id"=>"16", "city_code"=> "1610", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN OGAN ILIR", "name"=>"OGAN ILIR"]);
        City::create(["id"=>"1611", "province_id"=>"16", "city_code"=> "1611", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN EMPAT LAWANG", "name"=>"EMPAT LAWANG"]);
        City::create(["id"=>"1612", "province_id"=>"16", "city_code"=> "1612", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PENUKAL ABAB LEMATANG ILIR", "name"=>"PENUKAL ABAB LEMATANG ILIR"]);
        City::create(["id"=>"1613", "province_id"=>"16", "city_code"=> "1613", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUSI RAWAS UTARA", "name"=>"MUSI RAWAS UTARA"]);
        City::create(["id"=>"1671", "province_id"=>"16", "city_code"=> "1671", "jenis" => "KOTA", "name_lengkap" => "KOTA PALEMBANG", "name"=>"PALEMBANG"]);
        City::create(["id"=>"1672", "province_id"=>"16", "city_code"=> "1672", "jenis" => "KOTA", "name_lengkap" => "KOTA PRABUMULIH", "name"=>"PRABUMULIH"]);
        City::create(["id"=>"1673", "province_id"=>"16", "city_code"=> "1673", "jenis" => "KOTA", "name_lengkap" => "KOTA PAGAR ALAM", "name"=>"PAGAR ALAM"]);
        City::create(["id"=>"1674", "province_id"=>"16", "city_code"=> "1674", "jenis" => "KOTA", "name_lengkap" => "KOTA LUBUKLINGGAU", "name"=>"LUBUKLINGGAU"]);
        City::create(["id"=>"1701", "province_id"=>"17", "city_code"=> "1701", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BENGKULU SELATAN", "name"=>"BENGKULU SELATAN"]);
        City::create(["id"=>"1702", "province_id"=>"17", "city_code"=> "1702", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN REJANG LEBONG", "name"=>"REJANG LEBONG"]);
        City::create(["id"=>"1703", "province_id"=>"17", "city_code"=> "1703", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BENGKULU UTARA", "name"=>"BENGKULU UTARA"]);
        City::create(["id"=>"1704", "province_id"=>"17", "city_code"=> "1704", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KAUR", "name"=>"KAUR"]);
        City::create(["id"=>"1705", "province_id"=>"17", "city_code"=> "1705", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SELUMA", "name"=>"SELUMA"]);
        City::create(["id"=>"1706", "province_id"=>"17", "city_code"=> "1706", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUKOMUKO", "name"=>"MUKOMUKO"]);
        City::create(["id"=>"1707", "province_id"=>"17", "city_code"=> "1707", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LEBONG", "name"=>"LEBONG"]);
        City::create(["id"=>"1708", "province_id"=>"17", "city_code"=> "1708", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPAHIANG", "name"=>"KEPAHIANG"]);
        City::create(["id"=>"1709", "province_id"=>"17", "city_code"=> "1709", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BENGKULU TENGAH", "name"=>"BENGKULU TENGAH"]);
        City::create(["id"=>"1771", "province_id"=>"17", "city_code"=> "1771", "jenis" => "KOTA", "name_lengkap" => "KOTA BENGKULU", "name"=>"BENGKULU"]);
        City::create(["id"=>"1801", "province_id"=>"18", "city_code"=> "1801", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMPUNG BARAT", "name"=>"LAMPUNG BARAT"]);
        City::create(["id"=>"1802", "province_id"=>"18", "city_code"=> "1802", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANGGAMUS", "name"=>"TANGGAMUS"]);
        City::create(["id"=>"1803", "province_id"=>"18", "city_code"=> "1803", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMPUNG SELATAN", "name"=>"LAMPUNG SELATAN"]);
        City::create(["id"=>"1804", "province_id"=>"18", "city_code"=> "1804", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMPUNG TIMUR", "name"=>"LAMPUNG TIMUR"]);
        City::create(["id"=>"1805", "province_id"=>"18", "city_code"=> "1805", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMPUNG TENGAH", "name"=>"LAMPUNG TENGAH"]);
        City::create(["id"=>"1806", "province_id"=>"18", "city_code"=> "1806", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMPUNG UTARA", "name"=>"LAMPUNG UTARA"]);
        City::create(["id"=>"1807", "province_id"=>"18", "city_code"=> "1807", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN WAY KANAN", "name"=>"WAY KANAN"]);
        City::create(["id"=>"1808", "province_id"=>"18", "city_code"=> "1808", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TULANGBAWANG", "name"=>"TULANGBAWANG"]);
        City::create(["id"=>"1809", "province_id"=>"18", "city_code"=> "1809", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PESAWARAN", "name"=>"PESAWARAN"]);
        City::create(["id"=>"1810", "province_id"=>"18", "city_code"=> "1810", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PRINGSEWU", "name"=>"PRINGSEWU"]);
        City::create(["id"=>"1811", "province_id"=>"18", "city_code"=> "1811", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MESUJI", "name"=>"MESUJI"]);
        City::create(["id"=>"1812", "province_id"=>"18", "city_code"=> "1812", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TULANG BAWANG BARAT", "name"=>"TULANG BAWANG BARAT"]);
        City::create(["id"=>"1813", "province_id"=>"18", "city_code"=> "1813", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PESISIR BARAT", "name"=>"PESISIR BARAT"]);
        City::create(["id"=>"1871", "province_id"=>"18", "city_code"=> "1871", "jenis" => "KOTA", "name_lengkap" => "KOTA BANDAR LAMPUNG", "name"=>"BANDAR LAMPUNG"]);
        City::create(["id"=>"1872", "province_id"=>"18", "city_code"=> "1872", "jenis" => "KOTA", "name_lengkap" => "KOTA METRO", "name"=>"METRO"]);
        City::create(["id"=>"1901", "province_id"=>"19", "city_code"=> "1901", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGKA", "name"=>"BANGKA"]);
        City::create(["id"=>"1902", "province_id"=>"19", "city_code"=> "1902", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BELITUNG", "name"=>"BELITUNG"]);
        City::create(["id"=>"1903", "province_id"=>"19", "city_code"=> "1903", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGKA BARAT", "name"=>"BANGKA BARAT"]);
        City::create(["id"=>"1904", "province_id"=>"19", "city_code"=> "1904", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGKA TENGAH", "name"=>"BANGKA TENGAH"]);
        City::create(["id"=>"1905", "province_id"=>"19", "city_code"=> "1905", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGKA SELATAN", "name"=>"BANGKA SELATAN"]);
        City::create(["id"=>"1906", "province_id"=>"19", "city_code"=> "1906", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BELITUNG TIMUR", "name"=>"BELITUNG TIMUR"]);
        City::create(["id"=>"1971", "province_id"=>"19", "city_code"=> "1971", "jenis" => "KOTA", "name_lengkap" => "KOTA PANGKAL PINANG", "name"=>"PANGKAL PINANG"]);
        City::create(["id"=>"2101", "province_id"=>"21", "city_code"=> "2101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KARIMUN", "name"=>"KARIMUN"]);
        City::create(["id"=>"2102", "province_id"=>"21", "city_code"=> "2102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BINTAN", "name"=>"BINTAN"]);
        City::create(["id"=>"2103", "province_id"=>"21", "city_code"=> "2103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NATUNA", "name"=>"NATUNA"]);
        City::create(["id"=>"2104", "province_id"=>"21", "city_code"=> "2104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LINGGA", "name"=>"LINGGA"]);
        City::create(["id"=>"2105", "province_id"=>"21", "city_code"=> "2105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN ANAMBAS", "name"=>"KEPULAUAN ANAMBAS"]);
        City::create(["id"=>"2171", "province_id"=>"21", "city_code"=> "2171", "jenis" => "KOTA", "name_lengkap" => "KOTA B A T A M", "name"=>"B A T A M"]);
        City::create(["id"=>"2172", "province_id"=>"21", "city_code"=> "2172", "jenis" => "KOTA", "name_lengkap" => "KOTA TANJUNG PINANG", "name"=>"TANJUNG PINANG"]);
        City::create(["id"=>"3101", "province_id"=>"31", "city_code"=> "3101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN SERIBU", "name"=>"KEPULAUAN SERIBU"]);
        City::create(["id"=>"3171", "province_id"=>"31", "city_code"=> "3171", "jenis" => "KOTA", "name_lengkap" => "KOTA JAKARTA SELATAN", "name"=>"JAKARTA SELATAN"]);
        City::create(["id"=>"3172", "province_id"=>"31", "city_code"=> "3172", "jenis" => "KOTA", "name_lengkap" => "KOTA JAKARTA TIMUR", "name"=>"JAKARTA TIMUR"]);
        City::create(["id"=>"3173", "province_id"=>"31", "city_code"=> "3173", "jenis" => "KOTA", "name_lengkap" => "KOTA JAKARTA PUSAT", "name"=>"JAKARTA PUSAT"]);
        City::create(["id"=>"3174", "province_id"=>"31", "city_code"=> "3174", "jenis" => "KOTA", "name_lengkap" => "KOTA JAKARTA BARAT", "name"=>"JAKARTA BARAT"]);
        City::create(["id"=>"3175", "province_id"=>"31", "city_code"=> "3175", "jenis" => "KOTA", "name_lengkap" => "KOTA JAKARTA UTARA", "name"=>"JAKARTA UTARA"]);
        City::create(["id"=>"3201", "province_id"=>"32", "city_code"=> "3201", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOGOR", "name"=>"BOGOR"]);
        City::create(["id"=>"3202", "province_id"=>"32", "city_code"=> "3202", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUKABUMI", "name"=>"SUKABUMI"]);
        City::create(["id"=>"3203", "province_id"=>"32", "city_code"=> "3203", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN CIANJUR", "name"=>"CIANJUR"]);
        City::create(["id"=>"3204", "province_id"=>"32", "city_code"=> "3204", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANDUNG", "name"=>"BANDUNG"]);
        City::create(["id"=>"3205", "province_id"=>"32", "city_code"=> "3205", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GARUT", "name"=>"GARUT"]);
        City::create(["id"=>"3206", "province_id"=>"32", "city_code"=> "3206", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TASIKMALAYA", "name"=>"TASIKMALAYA"]);
        City::create(["id"=>"3207", "province_id"=>"32", "city_code"=> "3207", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN CIAMIS", "name"=>"CIAMIS"]);
        City::create(["id"=>"3208", "province_id"=>"32", "city_code"=> "3208", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUNINGAN", "name"=>"KUNINGAN"]);
        City::create(["id"=>"3209", "province_id"=>"32", "city_code"=> "3209", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN CIREBON", "name"=>"CIREBON"]);
        City::create(["id"=>"3210", "province_id"=>"32", "city_code"=> "3210", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAJALENGKA", "name"=>"MAJALENGKA"]);
        City::create(["id"=>"3211", "province_id"=>"32", "city_code"=> "3211", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMEDANG", "name"=>"SUMEDANG"]);
        City::create(["id"=>"3212", "province_id"=>"32", "city_code"=> "3212", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN INDRAMAYU", "name"=>"INDRAMAYU"]);
        City::create(["id"=>"3213", "province_id"=>"32", "city_code"=> "3213", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUBANG", "name"=>"SUBANG"]);
        City::create(["id"=>"3214", "province_id"=>"32", "city_code"=> "3214", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PURWAKARTA", "name"=>"PURWAKARTA"]);
        City::create(["id"=>"3215", "province_id"=>"32", "city_code"=> "3215", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KARAWANG", "name"=>"KARAWANG"]);
        City::create(["id"=>"3216", "province_id"=>"32", "city_code"=> "3216", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BEKASI", "name"=>"BEKASI"]);
        City::create(["id"=>"3217", "province_id"=>"32", "city_code"=> "3217", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANDUNG BARAT", "name"=>"BANDUNG BARAT"]);
        City::create(["id"=>"3218", "province_id"=>"32", "city_code"=> "3218", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PANGANDARAN", "name"=>"PANGANDARAN"]);
        City::create(["id"=>"3271", "province_id"=>"32", "city_code"=> "3271", "jenis" => "KOTA", "name_lengkap" => "KOTA BOGOR", "name"=>"BOGOR"]);
        City::create(["id"=>"3272", "province_id"=>"32", "city_code"=> "3272", "jenis" => "KOTA", "name_lengkap" => "KOTA SUKABUMI", "name"=>"SUKABUMI"]);
        City::create(["id"=>"3273", "province_id"=>"32", "city_code"=> "3273", "jenis" => "KOTA", "name_lengkap" => "KOTA BANDUNG", "name"=>"BANDUNG"]);
        City::create(["id"=>"3274", "province_id"=>"32", "city_code"=> "3274", "jenis" => "KOTA", "name_lengkap" => "KOTA CIREBON", "name"=>"CIREBON"]);
        City::create(["id"=>"3275", "province_id"=>"32", "city_code"=> "3275", "jenis" => "KOTA", "name_lengkap" => "KOTA BEKASI", "name"=>"BEKASI"]);
        City::create(["id"=>"3276", "province_id"=>"32", "city_code"=> "3276", "jenis" => "KOTA", "name_lengkap" => "KOTA DEPOK", "name"=>"DEPOK"]);
        City::create(["id"=>"3277", "province_id"=>"32", "city_code"=> "3277", "jenis" => "KOTA", "name_lengkap" => "KOTA CIMAHI", "name"=>"CIMAHI"]);
        City::create(["id"=>"3278", "province_id"=>"32", "city_code"=> "3278", "jenis" => "KOTA", "name_lengkap" => "KOTA TASIKMALAYA", "name"=>"TASIKMALAYA"]);
        City::create(["id"=>"3279", "province_id"=>"32", "city_code"=> "3279", "jenis" => "KOTA", "name_lengkap" => "KOTA BANJAR", "name"=>"BANJAR"]);
        City::create(["id"=>"3301", "province_id"=>"33", "city_code"=> "3301", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN CILACAP", "name"=>"CILACAP"]);
        City::create(["id"=>"3302", "province_id"=>"33", "city_code"=> "3302", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANYUMAS", "name"=>"BANYUMAS"]);
        City::create(["id"=>"3303", "province_id"=>"33", "city_code"=> "3303", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PURBALINGGA", "name"=>"PURBALINGGA"]);
        City::create(["id"=>"3304", "province_id"=>"33", "city_code"=> "3304", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANJARNEGARA", "name"=>"BANJARNEGARA"]);
        City::create(["id"=>"3305", "province_id"=>"33", "city_code"=> "3305", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEBUMEN", "name"=>"KEBUMEN"]);
        City::create(["id"=>"3306", "province_id"=>"33", "city_code"=> "3306", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PURWOREJO", "name"=>"PURWOREJO"]);
        City::create(["id"=>"3307", "province_id"=>"33", "city_code"=> "3307", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN WONOSOBO", "name"=>"WONOSOBO"]);
        City::create(["id"=>"3308", "province_id"=>"33", "city_code"=> "3308", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAGELANG", "name"=>"MAGELANG"]);
        City::create(["id"=>"3309", "province_id"=>"33", "city_code"=> "3309", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOYOLALI", "name"=>"BOYOLALI"]);
        City::create(["id"=>"3310", "province_id"=>"33", "city_code"=> "3310", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KLATEN", "name"=>"KLATEN"]);
        City::create(["id"=>"3311", "province_id"=>"33", "city_code"=> "3311", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUKOHARJO", "name"=>"SUKOHARJO"]);
        City::create(["id"=>"3312", "province_id"=>"33", "city_code"=> "3312", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN WONOGIRI", "name"=>"WONOGIRI"]);
        City::create(["id"=>"3313", "province_id"=>"33", "city_code"=> "3313", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KARANGANYAR", "name"=>"KARANGANYAR"]);
        City::create(["id"=>"3314", "province_id"=>"33", "city_code"=> "3314", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SRAGEN", "name"=>"SRAGEN"]);
        City::create(["id"=>"3315", "province_id"=>"33", "city_code"=> "3315", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GROBOGAN", "name"=>"GROBOGAN"]);
        City::create(["id"=>"3316", "province_id"=>"33", "city_code"=> "3316", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BLORA", "name"=>"BLORA"]);
        City::create(["id"=>"3317", "province_id"=>"33", "city_code"=> "3317", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN REMBANG", "name"=>"REMBANG"]);
        City::create(["id"=>"3318", "province_id"=>"33", "city_code"=> "3318", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PATI", "name"=>"PATI"]);
        City::create(["id"=>"3319", "province_id"=>"33", "city_code"=> "3319", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUDUS", "name"=>"KUDUS"]);
        City::create(["id"=>"3320", "province_id"=>"33", "city_code"=> "3320", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JEPARA", "name"=>"JEPARA"]);
        City::create(["id"=>"3321", "province_id"=>"33", "city_code"=> "3321", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DEMAK", "name"=>"DEMAK"]);
        City::create(["id"=>"3322", "province_id"=>"33", "city_code"=> "3322", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SEMARANG", "name"=>"SEMARANG"]);
        City::create(["id"=>"3323", "province_id"=>"33", "city_code"=> "3323", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TEMANGGUNG", "name"=>"TEMANGGUNG"]);
        City::create(["id"=>"3324", "province_id"=>"33", "city_code"=> "3324", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KENDAL", "name"=>"KENDAL"]);
        City::create(["id"=>"3325", "province_id"=>"33", "city_code"=> "3325", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BATANG", "name"=>"BATANG"]);
        City::create(["id"=>"3326", "province_id"=>"33", "city_code"=> "3326", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PEKALONGAN", "name"=>"PEKALONGAN"]);
        City::create(["id"=>"3327", "province_id"=>"33", "city_code"=> "3327", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PEMALANG", "name"=>"PEMALANG"]);
        City::create(["id"=>"3328", "province_id"=>"33", "city_code"=> "3328", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TEGAL", "name"=>"TEGAL"]);
        City::create(["id"=>"3329", "province_id"=>"33", "city_code"=> "3329", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BREBES", "name"=>"BREBES"]);
        City::create(["id"=>"3371", "province_id"=>"33", "city_code"=> "3371", "jenis" => "KOTA", "name_lengkap" => "KOTA MAGELANG", "name"=>"MAGELANG"]);
        City::create(["id"=>"3372", "province_id"=>"33", "city_code"=> "3372", "jenis" => "KOTA", "name_lengkap" => "KOTA SURAKARTA", "name"=>"SURAKARTA"]);
        City::create(["id"=>"3373", "province_id"=>"33", "city_code"=> "3373", "jenis" => "KOTA", "name_lengkap" => "KOTA SALATIGA", "name"=>"SALATIGA"]);
        City::create(["id"=>"3374", "province_id"=>"33", "city_code"=> "3374", "jenis" => "KOTA", "name_lengkap" => "KOTA SEMARANG", "name"=>"SEMARANG"]);
        City::create(["id"=>"3375", "province_id"=>"33", "city_code"=> "3375", "jenis" => "KOTA", "name_lengkap" => "KOTA PEKALONGAN", "name"=>"PEKALONGAN"]);
        City::create(["id"=>"3376", "province_id"=>"33", "city_code"=> "3376", "jenis" => "KOTA", "name_lengkap" => "KOTA TEGAL", "name"=>"TEGAL"]);
        City::create(["id"=>"3401", "province_id"=>"34", "city_code"=> "3401", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KULON PROGO", "name"=>"KULON PROGO"]);
        City::create(["id"=>"3402", "province_id"=>"34", "city_code"=> "3402", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANTUL", "name"=>"BANTUL"]);
        City::create(["id"=>"3403", "province_id"=>"34", "city_code"=> "3403", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GUNUNG KIDUL", "name"=>"GUNUNG KIDUL"]);
        City::create(["id"=>"3404", "province_id"=>"34", "city_code"=> "3404", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SLEMAN", "name"=>"SLEMAN"]);
        City::create(["id"=>"3471", "province_id"=>"34", "city_code"=> "3471", "jenis" => "KOTA", "name_lengkap" => "KOTA YOGYAKARTA", "name"=>"YOGYAKARTA"]);
        City::create(["id"=>"3501", "province_id"=>"35", "city_code"=> "3501", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PACITAN", "name"=>"PACITAN"]);
        City::create(["id"=>"3502", "province_id"=>"35", "city_code"=> "3502", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PONOROGO", "name"=>"PONOROGO"]);
        City::create(["id"=>"3503", "province_id"=>"35", "city_code"=> "3503", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TRENGGALEK", "name"=>"TRENGGALEK"]);
        City::create(["id"=>"3504", "province_id"=>"35", "city_code"=> "3504", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TULUNGAGUNG", "name"=>"TULUNGAGUNG"]);
        City::create(["id"=>"3505", "province_id"=>"35", "city_code"=> "3505", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BLITAR", "name"=>"BLITAR"]);
        City::create(["id"=>"3506", "province_id"=>"35", "city_code"=> "3506", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEDIRI", "name"=>"KEDIRI"]);
        City::create(["id"=>"3507", "province_id"=>"35", "city_code"=> "3507", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALANG", "name"=>"MALANG"]);
        City::create(["id"=>"3508", "province_id"=>"35", "city_code"=> "3508", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LUMAJANG", "name"=>"LUMAJANG"]);
        City::create(["id"=>"3509", "province_id"=>"35", "city_code"=> "3509", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JEMBER", "name"=>"JEMBER"]);
        City::create(["id"=>"3510", "province_id"=>"35", "city_code"=> "3510", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANYUWANGI", "name"=>"BANYUWANGI"]);
        City::create(["id"=>"3511", "province_id"=>"35", "city_code"=> "3511", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BONDOWOSO", "name"=>"BONDOWOSO"]);
        City::create(["id"=>"3512", "province_id"=>"35", "city_code"=> "3512", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SITUBONDO", "name"=>"SITUBONDO"]);
        City::create(["id"=>"3513", "province_id"=>"35", "city_code"=> "3513", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PROBOLINGGO", "name"=>"PROBOLINGGO"]);
        City::create(["id"=>"3514", "province_id"=>"35", "city_code"=> "3514", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PASURUAN", "name"=>"PASURUAN"]);
        City::create(["id"=>"3515", "province_id"=>"35", "city_code"=> "3515", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIDOARJO", "name"=>"SIDOARJO"]);
        City::create(["id"=>"3516", "province_id"=>"35", "city_code"=> "3516", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MOJOKERTO", "name"=>"MOJOKERTO"]);
        City::create(["id"=>"3517", "province_id"=>"35", "city_code"=> "3517", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JOMBANG", "name"=>"JOMBANG"]);
        City::create(["id"=>"3518", "province_id"=>"35", "city_code"=> "3518", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NGANJUK", "name"=>"NGANJUK"]);
        City::create(["id"=>"3519", "province_id"=>"35", "city_code"=> "3519", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MADIUN", "name"=>"MADIUN"]);
        City::create(["id"=>"3520", "province_id"=>"35", "city_code"=> "3520", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAGETAN", "name"=>"MAGETAN"]);
        City::create(["id"=>"3521", "province_id"=>"35", "city_code"=> "3521", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NGAWI", "name"=>"NGAWI"]);
        City::create(["id"=>"3522", "province_id"=>"35", "city_code"=> "3522", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOJONEGORO", "name"=>"BOJONEGORO"]);
        City::create(["id"=>"3523", "province_id"=>"35", "city_code"=> "3523", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TUBAN", "name"=>"TUBAN"]);
        City::create(["id"=>"3524", "province_id"=>"35", "city_code"=> "3524", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMONGAN", "name"=>"LAMONGAN"]);
        City::create(["id"=>"3525", "province_id"=>"35", "city_code"=> "3525", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GRESIK", "name"=>"GRESIK"]);
        City::create(["id"=>"3526", "province_id"=>"35", "city_code"=> "3526", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGKALAN", "name"=>"BANGKALAN"]);
        City::create(["id"=>"3527", "province_id"=>"35", "city_code"=> "3527", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SAMPANG", "name"=>"SAMPANG"]);
        City::create(["id"=>"3528", "province_id"=>"35", "city_code"=> "3528", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PAMEKASAN", "name"=>"PAMEKASAN"]);
        City::create(["id"=>"3529", "province_id"=>"35", "city_code"=> "3529", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMENEP", "name"=>"SUMENEP"]);
        City::create(["id"=>"3571", "province_id"=>"35", "city_code"=> "3571", "jenis" => "KOTA", "name_lengkap" => "KOTA KEDIRI", "name"=>"KEDIRI"]);
        City::create(["id"=>"3572", "province_id"=>"35", "city_code"=> "3572", "jenis" => "KOTA", "name_lengkap" => "KOTA BLITAR", "name"=>"BLITAR"]);
        City::create(["id"=>"3573", "province_id"=>"35", "city_code"=> "3573", "jenis" => "KOTA", "name_lengkap" => "KOTA MALANG", "name"=>"MALANG"]);
        City::create(["id"=>"3574", "province_id"=>"35", "city_code"=> "3574", "jenis" => "KOTA", "name_lengkap" => "KOTA PROBOLINGGO", "name"=>"PROBOLINGGO"]);
        City::create(["id"=>"3575", "province_id"=>"35", "city_code"=> "3575", "jenis" => "KOTA", "name_lengkap" => "KOTA PASURUAN", "name"=>"PASURUAN"]);
        City::create(["id"=>"3576", "province_id"=>"35", "city_code"=> "3576", "jenis" => "KOTA", "name_lengkap" => "KOTA MOJOKERTO", "name"=>"MOJOKERTO"]);
        City::create(["id"=>"3577", "province_id"=>"35", "city_code"=> "3577", "jenis" => "KOTA", "name_lengkap" => "KOTA MADIUN", "name"=>"MADIUN"]);
        City::create(["id"=>"3578", "province_id"=>"35", "city_code"=> "3578", "jenis" => "KOTA", "name_lengkap" => "KOTA SURABAYA", "name"=>"SURABAYA"]);
        City::create(["id"=>"3579", "province_id"=>"35", "city_code"=> "3579", "jenis" => "KOTA", "name_lengkap" => "KOTA BATU", "name"=>"BATU"]);
        City::create(["id"=>"3601", "province_id"=>"36", "city_code"=> "3601", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PANDEGLANG", "name"=>"PANDEGLANG"]);
        City::create(["id"=>"3602", "province_id"=>"36", "city_code"=> "3602", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LEBAK", "name"=>"LEBAK"]);
        City::create(["id"=>"3603", "province_id"=>"36", "city_code"=> "3603", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANGERANG", "name"=>"TANGERANG"]);
        City::create(["id"=>"3604", "province_id"=>"36", "city_code"=> "3604", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SERANG", "name"=>"SERANG"]);
        City::create(["id"=>"3671", "province_id"=>"36", "city_code"=> "3671", "jenis" => "KOTA", "name_lengkap" => "KOTA TANGERANG", "name"=>"TANGERANG"]);
        City::create(["id"=>"3672", "province_id"=>"36", "city_code"=> "3672", "jenis" => "KOTA", "name_lengkap" => "KOTA CILEGON", "name"=>"CILEGON"]);
        City::create(["id"=>"3673", "province_id"=>"36", "city_code"=> "3673", "jenis" => "KOTA", "name_lengkap" => "KOTA SERANG", "name"=>"SERANG"]);
        City::create(["id"=>"3674", "province_id"=>"36", "city_code"=> "3674", "jenis" => "KOTA", "name_lengkap" => "KOTA TANGERANG SELATAN", "name"=>"TANGERANG SELATAN"]);
        City::create(["id"=>"5101", "province_id"=>"51", "city_code"=> "5101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JEMBRANA", "name"=>"JEMBRANA"]);
        City::create(["id"=>"5102", "province_id"=>"51", "city_code"=> "5102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TABANAN", "name"=>"TABANAN"]);
        City::create(["id"=>"5103", "province_id"=>"51", "city_code"=> "5103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BADUNG", "name"=>"BADUNG"]);
        City::create(["id"=>"5104", "province_id"=>"51", "city_code"=> "5104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GIANYAR", "name"=>"GIANYAR"]);
        City::create(["id"=>"5105", "province_id"=>"51", "city_code"=> "5105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KLUNGKUNG", "name"=>"KLUNGKUNG"]);
        City::create(["id"=>"5106", "province_id"=>"51", "city_code"=> "5106", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGLI", "name"=>"BANGLI"]);
        City::create(["id"=>"5107", "province_id"=>"51", "city_code"=> "5107", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KARANG ASEM", "name"=>"KARANG ASEM"]);
        City::create(["id"=>"5108", "province_id"=>"51", "city_code"=> "5108", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BULELENG", "name"=>"BULELENG"]);
        City::create(["id"=>"5171", "province_id"=>"51", "city_code"=> "5171", "jenis" => "KOTA", "name_lengkap" => "KOTA DENPASAR", "name"=>"DENPASAR"]);
        City::create(["id"=>"5201", "province_id"=>"52", "city_code"=> "5201", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LOMBOK BARAT", "name"=>"LOMBOK BARAT"]);
        City::create(["id"=>"5202", "province_id"=>"52", "city_code"=> "5202", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LOMBOK TENGAH", "name"=>"LOMBOK TENGAH"]);
        City::create(["id"=>"5203", "province_id"=>"52", "city_code"=> "5203", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LOMBOK TIMUR", "name"=>"LOMBOK TIMUR"]);
        City::create(["id"=>"5204", "province_id"=>"52", "city_code"=> "5204", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMBAWA", "name"=>"SUMBAWA"]);
        City::create(["id"=>"5205", "province_id"=>"52", "city_code"=> "5205", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DOMPU", "name"=>"DOMPU"]);
        City::create(["id"=>"5206", "province_id"=>"52", "city_code"=> "5206", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BIMA", "name"=>"BIMA"]);
        City::create(["id"=>"5207", "province_id"=>"52", "city_code"=> "5207", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMBAWA BARAT", "name"=>"SUMBAWA BARAT"]);
        City::create(["id"=>"5208", "province_id"=>"52", "city_code"=> "5208", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LOMBOK UTARA", "name"=>"LOMBOK UTARA"]);
        City::create(["id"=>"5271", "province_id"=>"52", "city_code"=> "5271", "jenis" => "KOTA", "name_lengkap" => "KOTA MATARAM", "name"=>"MATARAM"]);
        City::create(["id"=>"5272", "province_id"=>"52", "city_code"=> "5272", "jenis" => "KOTA", "name_lengkap" => "KOTA BIMA", "name"=>"BIMA"]);
        City::create(["id"=>"5301", "province_id"=>"53", "city_code"=> "5301", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMBA BARAT", "name"=>"SUMBA BARAT"]);
        City::create(["id"=>"5302", "province_id"=>"53", "city_code"=> "5302", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMBA TIMUR", "name"=>"SUMBA TIMUR"]);
        City::create(["id"=>"5303", "province_id"=>"53", "city_code"=> "5303", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUPANG", "name"=>"KUPANG"]);
        City::create(["id"=>"5304", "province_id"=>"53", "city_code"=> "5304", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TIMOR TENGAH SELATAN", "name"=>"TIMOR TENGAH SELATAN"]);
        City::create(["id"=>"5305", "province_id"=>"53", "city_code"=> "5305", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TIMOR TENGAH UTARA", "name"=>"TIMOR TENGAH UTARA"]);
        City::create(["id"=>"5306", "province_id"=>"53", "city_code"=> "5306", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BELU", "name"=>"BELU"]);
        City::create(["id"=>"5307", "province_id"=>"53", "city_code"=> "5307", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ALOR", "name"=>"ALOR"]);
        City::create(["id"=>"5308", "province_id"=>"53", "city_code"=> "5308", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LEMBATA", "name"=>"LEMBATA"]);
        City::create(["id"=>"5309", "province_id"=>"53", "city_code"=> "5309", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN FLORES TIMUR", "name"=>"FLORES TIMUR"]);
        City::create(["id"=>"5310", "province_id"=>"53", "city_code"=> "5310", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIKKA", "name"=>"SIKKA"]);
        City::create(["id"=>"5311", "province_id"=>"53", "city_code"=> "5311", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ENDE", "name"=>"ENDE"]);
        City::create(["id"=>"5312", "province_id"=>"53", "city_code"=> "5312", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NGADA", "name"=>"NGADA"]);
        City::create(["id"=>"5313", "province_id"=>"53", "city_code"=> "5313", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MANGGARAI", "name"=>"MANGGARAI"]);
        City::create(["id"=>"5314", "province_id"=>"53", "city_code"=> "5314", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ROTE NDAO", "name"=>"ROTE NDAO"]);
        City::create(["id"=>"5315", "province_id"=>"53", "city_code"=> "5315", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MANGGARAI BARAT", "name"=>"MANGGARAI BARAT"]);
        City::create(["id"=>"5316", "province_id"=>"53", "city_code"=> "5316", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMBA TENGAH", "name"=>"SUMBA TENGAH"]);
        City::create(["id"=>"5317", "province_id"=>"53", "city_code"=> "5317", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUMBA BARAT DAYA", "name"=>"SUMBA BARAT DAYA"]);
        City::create(["id"=>"5318", "province_id"=>"53", "city_code"=> "5318", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NAGEKEO", "name"=>"NAGEKEO"]);
        City::create(["id"=>"5319", "province_id"=>"53", "city_code"=> "5319", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MANGGARAI TIMUR", "name"=>"MANGGARAI TIMUR"]);
        City::create(["id"=>"5320", "province_id"=>"53", "city_code"=> "5320", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SABU RAIJUA", "name"=>"SABU RAIJUA"]);
        City::create(["id"=>"5321", "province_id"=>"53", "city_code"=> "5321", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALAKA", "name"=>"MALAKA"]);
        City::create(["id"=>"5371", "province_id"=>"53", "city_code"=> "5371", "jenis" => "KOTA", "name_lengkap" => "KOTA KUPANG", "name"=>"KUPANG"]);
        City::create(["id"=>"6101", "province_id"=>"61", "city_code"=> "6101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SAMBAS", "name"=>"SAMBAS"]);
        City::create(["id"=>"6102", "province_id"=>"61", "city_code"=> "6102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BENGKAYANG", "name"=>"BENGKAYANG"]);
        City::create(["id"=>"6103", "province_id"=>"61", "city_code"=> "6103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LANDAK", "name"=>"LANDAK"]);
        City::create(["id"=>"6104", "province_id"=>"61", "city_code"=> "6104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MEMPAWAH", "name"=>"MEMPAWAH"]);
        City::create(["id"=>"6105", "province_id"=>"61", "city_code"=> "6105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SANGGAU", "name"=>"SANGGAU"]);
        City::create(["id"=>"6106", "province_id"=>"61", "city_code"=> "6106", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KETAPANG", "name"=>"KETAPANG"]);
        City::create(["id"=>"6107", "province_id"=>"61", "city_code"=> "6107", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SINTANG", "name"=>"SINTANG"]);
        City::create(["id"=>"6108", "province_id"=>"61", "city_code"=> "6108", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KAPUAS HULU", "name"=>"KAPUAS HULU"]);
        City::create(["id"=>"6109", "province_id"=>"61", "city_code"=> "6109", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SEKADAU", "name"=>"SEKADAU"]);
        City::create(["id"=>"6110", "province_id"=>"61", "city_code"=> "6110", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MELAWI", "name"=>"MELAWI"]);
        City::create(["id"=>"6111", "province_id"=>"61", "city_code"=> "6111", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KAYONG UTARA", "name"=>"KAYONG UTARA"]);
        City::create(["id"=>"6112", "province_id"=>"61", "city_code"=> "6112", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUBU RAYA", "name"=>"KUBU RAYA"]);
        City::create(["id"=>"6171", "province_id"=>"61", "city_code"=> "6171", "jenis" => "KOTA", "name_lengkap" => "KOTA PONTIANAK", "name"=>"PONTIANAK"]);
        City::create(["id"=>"6172", "province_id"=>"61", "city_code"=> "6172", "jenis" => "KOTA", "name_lengkap" => "KOTA SINGKAWANG", "name"=>"SINGKAWANG"]);
        City::create(["id"=>"6201", "province_id"=>"62", "city_code"=> "6201", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KOTAWARINGIN BARAT", "name"=>"KOTAWARINGIN BARAT"]);
        City::create(["id"=>"6202", "province_id"=>"62", "city_code"=> "6202", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KOTAWARINGIN TIMUR", "name"=>"KOTAWARINGIN TIMUR"]);
        City::create(["id"=>"6203", "province_id"=>"62", "city_code"=> "6203", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KAPUAS", "name"=>"KAPUAS"]);
        City::create(["id"=>"6204", "province_id"=>"62", "city_code"=> "6204", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BARITO SELATAN", "name"=>"BARITO SELATAN"]);
        City::create(["id"=>"6205", "province_id"=>"62", "city_code"=> "6205", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BARITO UTARA", "name"=>"BARITO UTARA"]);
        City::create(["id"=>"6206", "province_id"=>"62", "city_code"=> "6206", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUKAMARA", "name"=>"SUKAMARA"]);
        City::create(["id"=>"6207", "province_id"=>"62", "city_code"=> "6207", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LAMANDAU", "name"=>"LAMANDAU"]);
        City::create(["id"=>"6208", "province_id"=>"62", "city_code"=> "6208", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SERUYAN", "name"=>"SERUYAN"]);
        City::create(["id"=>"6209", "province_id"=>"62", "city_code"=> "6209", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KATINGAN", "name"=>"KATINGAN"]);
        City::create(["id"=>"6210", "province_id"=>"62", "city_code"=> "6210", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PULANG PISAU", "name"=>"PULANG PISAU"]);
        City::create(["id"=>"6211", "province_id"=>"62", "city_code"=> "6211", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GUNUNG MAS", "name"=>"GUNUNG MAS"]);
        City::create(["id"=>"6212", "province_id"=>"62", "city_code"=> "6212", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BARITO TIMUR", "name"=>"BARITO TIMUR"]);
        City::create(["id"=>"6213", "province_id"=>"62", "city_code"=> "6213", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MURUNG RAYA", "name"=>"MURUNG RAYA"]);
        City::create(["id"=>"6271", "province_id"=>"62", "city_code"=> "6271", "jenis" => "KOTA", "name_lengkap" => "KOTA PALANGKA RAYA", "name"=>"PALANGKA RAYA"]);
        City::create(["id"=>"6301", "province_id"=>"63", "city_code"=> "6301", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANAH LAUT", "name"=>"TANAH LAUT"]);
        City::create(["id"=>"6302", "province_id"=>"63", "city_code"=> "6302", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KOTA BARU", "name"=>"KOTA BARU"]);
        City::create(["id"=>"6303", "province_id"=>"63", "city_code"=> "6303", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANJAR", "name"=>"BANJAR"]);
        City::create(["id"=>"6304", "province_id"=>"63", "city_code"=> "6304", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BARITO KUALA", "name"=>"BARITO KUALA"]);
        City::create(["id"=>"6305", "province_id"=>"63", "city_code"=> "6305", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TAPIN", "name"=>"TAPIN"]);
        City::create(["id"=>"6306", "province_id"=>"63", "city_code"=> "6306", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HULU SUNGAI SELATAN", "name"=>"HULU SUNGAI SELATAN"]);
        City::create(["id"=>"6307", "province_id"=>"63", "city_code"=> "6307", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HULU SUNGAI TENGAH", "name"=>"HULU SUNGAI TENGAH"]);
        City::create(["id"=>"6308", "province_id"=>"63", "city_code"=> "6308", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HULU SUNGAI UTARA", "name"=>"HULU SUNGAI UTARA"]);
        City::create(["id"=>"6309", "province_id"=>"63", "city_code"=> "6309", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TABALONG", "name"=>"TABALONG"]);
        City::create(["id"=>"6310", "province_id"=>"63", "city_code"=> "6310", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANAH BUMBU", "name"=>"TANAH BUMBU"]);
        City::create(["id"=>"6311", "province_id"=>"63", "city_code"=> "6311", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BALANGAN", "name"=>"BALANGAN"]);
        City::create(["id"=>"6371", "province_id"=>"63", "city_code"=> "6371", "jenis" => "KOTA", "name_lengkap" => "KOTA BANJARMASIN", "name"=>"BANJARMASIN"]);
        City::create(["id"=>"6372", "province_id"=>"63", "city_code"=> "6372", "jenis" => "KOTA", "name_lengkap" => "KOTA BANJAR BARU", "name"=>"BANJAR BARU"]);
        City::create(["id"=>"6401", "province_id"=>"64", "city_code"=> "6401", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PASER", "name"=>"PASER"]);
        City::create(["id"=>"6402", "province_id"=>"64", "city_code"=> "6402", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUTAI BARAT", "name"=>"KUTAI BARAT"]);
        City::create(["id"=>"6403", "province_id"=>"64", "city_code"=> "6403", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUTAI KARTANEGARA", "name"=>"KUTAI KARTANEGARA"]);
        City::create(["id"=>"6404", "province_id"=>"64", "city_code"=> "6404", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KUTAI TIMUR", "name"=>"KUTAI TIMUR"]);
        City::create(["id"=>"6405", "province_id"=>"64", "city_code"=> "6405", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BERAU", "name"=>"BERAU"]);
        City::create(["id"=>"6409", "province_id"=>"64", "city_code"=> "6409", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PENAJAM PASER UTARA", "name"=>"PENAJAM PASER UTARA"]);
        City::create(["id"=>"6411", "province_id"=>"64", "city_code"=> "6411", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAHAKAM HULU", "name"=>"MAHAKAM HULU"]);
        City::create(["id"=>"6471", "province_id"=>"64", "city_code"=> "6471", "jenis" => "KOTA", "name_lengkap" => "KOTA BALIKPAPAN", "name"=>"BALIKPAPAN"]);
        City::create(["id"=>"6472", "province_id"=>"64", "city_code"=> "6472", "jenis" => "KOTA", "name_lengkap" => "KOTA SAMARINDA", "name"=>"SAMARINDA"]);
        City::create(["id"=>"6474", "province_id"=>"64", "city_code"=> "6474", "jenis" => "KOTA", "name_lengkap" => "KOTA BONTANG", "name"=>"BONTANG"]);
        City::create(["id"=>"6501", "province_id"=>"65", "city_code"=> "6501", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALINAU", "name"=>"MALINAU"]);
        City::create(["id"=>"6502", "province_id"=>"65", "city_code"=> "6502", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BULUNGAN", "name"=>"BULUNGAN"]);
        City::create(["id"=>"6503", "province_id"=>"65", "city_code"=> "6503", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANA TIDUNG", "name"=>"TANA TIDUNG"]);
        City::create(["id"=>"6504", "province_id"=>"65", "city_code"=> "6504", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NUNUKAN", "name"=>"NUNUKAN"]);
        City::create(["id"=>"6571", "province_id"=>"65", "city_code"=> "6571", "jenis" => "KOTA", "name_lengkap" => "KOTA TARAKAN", "name"=>"TARAKAN"]);
        City::create(["id"=>"7101", "province_id"=>"71", "city_code"=> "7101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOLAANG MONGONDOW", "name"=>"BOLAANG MONGONDOW"]);
        City::create(["id"=>"7102", "province_id"=>"71", "city_code"=> "7102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MINAHASA", "name"=>"MINAHASA"]);
        City::create(["id"=>"7103", "province_id"=>"71", "city_code"=> "7103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN SANGIHE", "name"=>"KEPULAUAN SANGIHE"]);
        City::create(["id"=>"7104", "province_id"=>"71", "city_code"=> "7104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN TALAUD", "name"=>"KEPULAUAN TALAUD"]);
        City::create(["id"=>"7105", "province_id"=>"71", "city_code"=> "7105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MINAHASA SELATAN", "name"=>"MINAHASA SELATAN"]);
        City::create(["id"=>"7106", "province_id"=>"71", "city_code"=> "7106", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MINAHASA UTARA", "name"=>"MINAHASA UTARA"]);
        City::create(["id"=>"7107", "province_id"=>"71", "city_code"=> "7107", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOLAANG MONGONDOW UTARA", "name"=>"BOLAANG MONGONDOW UTARA"]);
        City::create(["id"=>"7108", "province_id"=>"71", "city_code"=> "7108", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIAU TAGULANDANG BIARO", "name"=>"SIAU TAGULANDANG BIARO"]);
        City::create(["id"=>"7109", "province_id"=>"71", "city_code"=> "7109", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MINAHASA TENGGARA", "name"=>"MINAHASA TENGGARA"]);
        City::create(["id"=>"7110", "province_id"=>"71", "city_code"=> "7110", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOLAANG MONGONDOW SELATAN", "name"=>"BOLAANG MONGONDOW SELATAN"]);
        City::create(["id"=>"7111", "province_id"=>"71", "city_code"=> "7111", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOLAANG MONGONDOW TIMUR", "name"=>"BOLAANG MONGONDOW TIMUR"]);
        City::create(["id"=>"7171", "province_id"=>"71", "city_code"=> "7171", "jenis" => "KOTA", "name_lengkap" => "KOTA MANADO", "name"=>"MANADO"]);
        City::create(["id"=>"7172", "province_id"=>"71", "city_code"=> "7172", "jenis" => "KOTA", "name_lengkap" => "KOTA BITUNG", "name"=>"BITUNG"]);
        City::create(["id"=>"7173", "province_id"=>"71", "city_code"=> "7173", "jenis" => "KOTA", "name_lengkap" => "KOTA TOMOHON", "name"=>"TOMOHON"]);
        City::create(["id"=>"7174", "province_id"=>"71", "city_code"=> "7174", "jenis" => "KOTA", "name_lengkap" => "KOTA KOTAMOBAGU", "name"=>"KOTAMOBAGU"]);
        City::create(["id"=>"7201", "province_id"=>"72", "city_code"=> "7201", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGGAI KEPULAUAN", "name"=>"BANGGAI KEPULAUAN"]);
        City::create(["id"=>"7202", "province_id"=>"72", "city_code"=> "7202", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGGAI", "name"=>"BANGGAI"]);
        City::create(["id"=>"7203", "province_id"=>"72", "city_code"=> "7203", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MOROWALI", "name"=>"MOROWALI"]);
        City::create(["id"=>"7204", "province_id"=>"72", "city_code"=> "7204", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN POSO", "name"=>"POSO"]);
        City::create(["id"=>"7205", "province_id"=>"72", "city_code"=> "7205", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DONGGALA", "name"=>"DONGGALA"]);
        City::create(["id"=>"7206", "province_id"=>"72", "city_code"=> "7206", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TOLI-TOLI", "name"=>"TOLI-TOLI"]);
        City::create(["id"=>"7207", "province_id"=>"72", "city_code"=> "7207", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BUOL", "name"=>"BUOL"]);
        City::create(["id"=>"7208", "province_id"=>"72", "city_code"=> "7208", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PARIGI MOUTONG", "name"=>"PARIGI MOUTONG"]);
        City::create(["id"=>"7209", "province_id"=>"72", "city_code"=> "7209", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TOJO UNA-UNA", "name"=>"TOJO UNA-UNA"]);
        City::create(["id"=>"7210", "province_id"=>"72", "city_code"=> "7210", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIGI", "name"=>"SIGI"]);
        City::create(["id"=>"7211", "province_id"=>"72", "city_code"=> "7211", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANGGAI LAUT", "name"=>"BANGGAI LAUT"]);
        City::create(["id"=>"7212", "province_id"=>"72", "city_code"=> "7212", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MOROWALI UTARA", "name"=>"MOROWALI UTARA"]);
        City::create(["id"=>"7271", "province_id"=>"72", "city_code"=> "7271", "jenis" => "KOTA", "name_lengkap" => "KOTA PALU", "name"=>"PALU"]);
        City::create(["id"=>"7301", "province_id"=>"73", "city_code"=> "7301", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN SELAYAR", "name"=>"KEPULAUAN SELAYAR"]);
        City::create(["id"=>"7302", "province_id"=>"73", "city_code"=> "7302", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BULUKUMBA", "name"=>"BULUKUMBA"]);
        City::create(["id"=>"7303", "province_id"=>"73", "city_code"=> "7303", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BANTAENG", "name"=>"BANTAENG"]);
        City::create(["id"=>"7304", "province_id"=>"73", "city_code"=> "7304", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JENEPONTO", "name"=>"JENEPONTO"]);
        City::create(["id"=>"7305", "province_id"=>"73", "city_code"=> "7305", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TAKALAR", "name"=>"TAKALAR"]);
        City::create(["id"=>"7306", "province_id"=>"73", "city_code"=> "7306", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GOWA", "name"=>"GOWA"]);
        City::create(["id"=>"7307", "province_id"=>"73", "city_code"=> "7307", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SINJAI", "name"=>"SINJAI"]);
        City::create(["id"=>"7308", "province_id"=>"73", "city_code"=> "7308", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAROS", "name"=>"MAROS"]);
        City::create(["id"=>"7309", "province_id"=>"73", "city_code"=> "7309", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PANGKAJENE DAN KEPULAUAN", "name"=>"PANGKAJENE DAN KEPULAUAN"]);
        City::create(["id"=>"7310", "province_id"=>"73", "city_code"=> "7310", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BARRU", "name"=>"BARRU"]);
        City::create(["id"=>"7311", "province_id"=>"73", "city_code"=> "7311", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BONE", "name"=>"BONE"]);
        City::create(["id"=>"7312", "province_id"=>"73", "city_code"=> "7312", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SOPPENG", "name"=>"SOPPENG"]);
        City::create(["id"=>"7313", "province_id"=>"73", "city_code"=> "7313", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN WAJO", "name"=>"WAJO"]);
        City::create(["id"=>"7314", "province_id"=>"73", "city_code"=> "7314", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SIDENRENG RAPPANG", "name"=>"SIDENRENG RAPPANG"]);
        City::create(["id"=>"7315", "province_id"=>"73", "city_code"=> "7315", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PINRANG", "name"=>"PINRANG"]);
        City::create(["id"=>"7316", "province_id"=>"73", "city_code"=> "7316", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ENREKANG", "name"=>"ENREKANG"]);
        City::create(["id"=>"7317", "province_id"=>"73", "city_code"=> "7317", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LUWU", "name"=>"LUWU"]);
        City::create(["id"=>"7318", "province_id"=>"73", "city_code"=> "7318", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TANA TORAJA", "name"=>"TANA TORAJA"]);
        City::create(["id"=>"7322", "province_id"=>"73", "city_code"=> "7322", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LUWU UTARA", "name"=>"LUWU UTARA"]);
        City::create(["id"=>"7325", "province_id"=>"73", "city_code"=> "7325", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LUWU TIMUR", "name"=>"LUWU TIMUR"]);
        City::create(["id"=>"7326", "province_id"=>"73", "city_code"=> "7326", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TORAJA UTARA", "name"=>"TORAJA UTARA"]);
        City::create(["id"=>"7371", "province_id"=>"73", "city_code"=> "7371", "jenis" => "KOTA", "name_lengkap" => "KOTA MAKASSAR", "name"=>"MAKASSAR"]);
        City::create(["id"=>"7372", "province_id"=>"73", "city_code"=> "7372", "jenis" => "KOTA", "name_lengkap" => "KOTA PAREPARE", "name"=>"PAREPARE"]);
        City::create(["id"=>"7373", "province_id"=>"73", "city_code"=> "7373", "jenis" => "KOTA", "name_lengkap" => "KOTA PALOPO", "name"=>"PALOPO"]);
        City::create(["id"=>"7401", "province_id"=>"74", "city_code"=> "7401", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BUTON", "name"=>"BUTON"]);
        City::create(["id"=>"7402", "province_id"=>"74", "city_code"=> "7402", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUNA", "name"=>"MUNA"]);
        City::create(["id"=>"7403", "province_id"=>"74", "city_code"=> "7403", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KONAWE", "name"=>"KONAWE"]);
        City::create(["id"=>"7404", "province_id"=>"74", "city_code"=> "7404", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KOLAKA", "name"=>"KOLAKA"]);
        City::create(["id"=>"7405", "province_id"=>"74", "city_code"=> "7405", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KONAWE SELATAN", "name"=>"KONAWE SELATAN"]);
        City::create(["id"=>"7406", "province_id"=>"74", "city_code"=> "7406", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOMBANA", "name"=>"BOMBANA"]);
        City::create(["id"=>"7407", "province_id"=>"74", "city_code"=> "7407", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN WAKATOBI", "name"=>"WAKATOBI"]);
        City::create(["id"=>"7408", "province_id"=>"74", "city_code"=> "7408", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KOLAKA UTARA", "name"=>"KOLAKA UTARA"]);
        City::create(["id"=>"7409", "province_id"=>"74", "city_code"=> "7409", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BUTON UTARA", "name"=>"BUTON UTARA"]);
        City::create(["id"=>"7410", "province_id"=>"74", "city_code"=> "7410", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KONAWE UTARA", "name"=>"KONAWE UTARA"]);
        City::create(["id"=>"7411", "province_id"=>"74", "city_code"=> "7411", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KOLAKA TIMUR", "name"=>"KOLAKA TIMUR"]);
        City::create(["id"=>"7412", "province_id"=>"74", "city_code"=> "7412", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KONAWE KEPULAUAN", "name"=>"KONAWE KEPULAUAN"]);
        City::create(["id"=>"7413", "province_id"=>"74", "city_code"=> "7413", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MUNA BARAT", "name"=>"MUNA BARAT"]);
        City::create(["id"=>"7414", "province_id"=>"74", "city_code"=> "7414", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BUTON TENGAH", "name"=>"BUTON TENGAH"]);
        City::create(["id"=>"7415", "province_id"=>"74", "city_code"=> "7415", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BUTON SELATAN", "name"=>"BUTON SELATAN"]);
        City::create(["id"=>"7471", "province_id"=>"74", "city_code"=> "7471", "jenis" => "KOTA", "name_lengkap" => "KOTA KENDARI", "name"=>"KENDARI"]);
        City::create(["id"=>"7472", "province_id"=>"74", "city_code"=> "7472", "jenis" => "KOTA", "name_lengkap" => "KOTA BAUBAU", "name"=>"BAUBAU"]);
        City::create(["id"=>"7501", "province_id"=>"75", "city_code"=> "7501", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOALEMO", "name"=>"BOALEMO"]);
        City::create(["id"=>"7502", "province_id"=>"75", "city_code"=> "7502", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GORONTALO", "name"=>"GORONTALO"]);
        City::create(["id"=>"7503", "province_id"=>"75", "city_code"=> "7503", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN POHUWATO", "name"=>"POHUWATO"]);
        City::create(["id"=>"7504", "province_id"=>"75", "city_code"=> "7504", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BONE BOLANGO", "name"=>"BONE BOLANGO"]);
        City::create(["id"=>"7505", "province_id"=>"75", "city_code"=> "7505", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN GORONTALO UTARA", "name"=>"GORONTALO UTARA"]);
        City::create(["id"=>"7571", "province_id"=>"75", "city_code"=> "7571", "jenis" => "KOTA", "name_lengkap" => "KOTA GORONTALO", "name"=>"GORONTALO"]);
        City::create(["id"=>"7601", "province_id"=>"76", "city_code"=> "7601", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAJENE", "name"=>"MAJENE"]);
        City::create(["id"=>"7602", "province_id"=>"76", "city_code"=> "7602", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN POLEWALI MANDAR", "name"=>"POLEWALI MANDAR"]);
        City::create(["id"=>"7603", "province_id"=>"76", "city_code"=> "7603", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAMASA", "name"=>"MAMASA"]);
        City::create(["id"=>"7604", "province_id"=>"76", "city_code"=> "7604", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAMUJU", "name"=>"MAMUJU"]);
        City::create(["id"=>"7605", "province_id"=>"76", "city_code"=> "7605", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAMUJU UTARA", "name"=>"MAMUJU UTARA"]);
        City::create(["id"=>"7606", "province_id"=>"76", "city_code"=> "7606", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAMUJU TENGAH", "name"=>"MAMUJU TENGAH"]);
        City::create(["id"=>"8101", "province_id"=>"81", "city_code"=> "8101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALUKU TENGGARA BARAT", "name"=>"MALUKU TENGGARA BARAT"]);
        City::create(["id"=>"8102", "province_id"=>"81", "city_code"=> "8102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALUKU TENGGARA", "name"=>"MALUKU TENGGARA"]);
        City::create(["id"=>"8103", "province_id"=>"81", "city_code"=> "8103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALUKU TENGAH", "name"=>"MALUKU TENGAH"]);
        City::create(["id"=>"8104", "province_id"=>"81", "city_code"=> "8104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BURU", "name"=>"BURU"]);
        City::create(["id"=>"8105", "province_id"=>"81", "city_code"=> "8105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN ARU", "name"=>"KEPULAUAN ARU"]);
        City::create(["id"=>"8106", "province_id"=>"81", "city_code"=> "8106", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SERAM BAGIAN BARAT", "name"=>"SERAM BAGIAN BARAT"]);
        City::create(["id"=>"8107", "province_id"=>"81", "city_code"=> "8107", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SERAM BAGIAN TIMUR", "name"=>"SERAM BAGIAN TIMUR"]);
        City::create(["id"=>"8108", "province_id"=>"81", "city_code"=> "8108", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MALUKU BARAT DAYA", "name"=>"MALUKU BARAT DAYA"]);
        City::create(["id"=>"8109", "province_id"=>"81", "city_code"=> "8109", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BURU SELATAN", "name"=>"BURU SELATAN"]);
        City::create(["id"=>"8171", "province_id"=>"81", "city_code"=> "8171", "jenis" => "KOTA", "name_lengkap" => "KOTA AMBON", "name"=>"AMBON"]);
        City::create(["id"=>"8172", "province_id"=>"81", "city_code"=> "8172", "jenis" => "KOTA", "name_lengkap" => "KOTA TUAL", "name"=>"TUAL"]);
        City::create(["id"=>"8201", "province_id"=>"82", "city_code"=> "8201", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HALMAHERA BARAT", "name"=>"HALMAHERA BARAT"]);
        City::create(["id"=>"8202", "province_id"=>"82", "city_code"=> "8202", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HALMAHERA TENGAH", "name"=>"HALMAHERA TENGAH"]);
        City::create(["id"=>"8203", "province_id"=>"82", "city_code"=> "8203", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN SULA", "name"=>"KEPULAUAN SULA"]);
        City::create(["id"=>"8204", "province_id"=>"82", "city_code"=> "8204", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HALMAHERA SELATAN", "name"=>"HALMAHERA SELATAN"]);
        City::create(["id"=>"8205", "province_id"=>"82", "city_code"=> "8205", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HALMAHERA UTARA", "name"=>"HALMAHERA UTARA"]);
        City::create(["id"=>"8206", "province_id"=>"82", "city_code"=> "8206", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN HALMAHERA TIMUR", "name"=>"HALMAHERA TIMUR"]);
        City::create(["id"=>"8207", "province_id"=>"82", "city_code"=> "8207", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PULAU MOROTAI", "name"=>"PULAU MOROTAI"]);
        City::create(["id"=>"8208", "province_id"=>"82", "city_code"=> "8208", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PULAU TALIABU", "name"=>"PULAU TALIABU"]);
        City::create(["id"=>"8271", "province_id"=>"82", "city_code"=> "8271", "jenis" => "KOTA", "name_lengkap" => "KOTA TERNATE", "name"=>"TERNATE"]);
        City::create(["id"=>"8272", "province_id"=>"82", "city_code"=> "8272", "jenis" => "KOTA", "name_lengkap" => "KOTA TIDORE KEPULAUAN", "name"=>"TIDORE KEPULAUAN"]);
        City::create(["id"=>"9101", "province_id"=>"91", "city_code"=> "9101", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN FAKFAK", "name"=>"FAKFAK"]);
        City::create(["id"=>"9102", "province_id"=>"91", "city_code"=> "9102", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KAIMANA", "name"=>"KAIMANA"]);
        City::create(["id"=>"9103", "province_id"=>"91", "city_code"=> "9103", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TELUK WONDAMA", "name"=>"TELUK WONDAMA"]);
        City::create(["id"=>"9104", "province_id"=>"91", "city_code"=> "9104", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TELUK BINTUNI", "name"=>"TELUK BINTUNI"]);
        City::create(["id"=>"9105", "province_id"=>"91", "city_code"=> "9105", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MANOKWARI", "name"=>"MANOKWARI"]);
        City::create(["id"=>"9106", "province_id"=>"91", "city_code"=> "9106", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SORONG SELATAN", "name"=>"SORONG SELATAN"]);
        City::create(["id"=>"9107", "province_id"=>"91", "city_code"=> "9107", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SORONG", "name"=>"SORONG"]);
        City::create(["id"=>"9108", "province_id"=>"91", "city_code"=> "9108", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN RAJA AMPAT", "name"=>"RAJA AMPAT"]);
        City::create(["id"=>"9109", "province_id"=>"91", "city_code"=> "9109", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TAMBRAUW", "name"=>"TAMBRAUW"]);
        City::create(["id"=>"9110", "province_id"=>"91", "city_code"=> "9110", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAYBRAT", "name"=>"MAYBRAT"]);
        City::create(["id"=>"9111", "province_id"=>"91", "city_code"=> "9111", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MANOKWARI SELATAN", "name"=>"MANOKWARI SELATAN"]);
        City::create(["id"=>"9112", "province_id"=>"91", "city_code"=> "9112", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PEGUNUNGAN ARFAK", "name"=>"PEGUNUNGAN ARFAK"]);
        City::create(["id"=>"9171", "province_id"=>"91", "city_code"=> "9171", "jenis" => "KOTA", "name_lengkap" => "KOTA SORONG", "name"=>"SORONG"]);
        City::create(["id"=>"9401", "province_id"=>"94", "city_code"=> "9401", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MERAUKE", "name"=>"MERAUKE"]);
        City::create(["id"=>"9402", "province_id"=>"94", "city_code"=> "9402", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JAYAWIJAYA", "name"=>"JAYAWIJAYA"]);
        City::create(["id"=>"9403", "province_id"=>"94", "city_code"=> "9403", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN JAYAPURA", "name"=>"JAYAPURA"]);
        City::create(["id"=>"9404", "province_id"=>"94", "city_code"=> "9404", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NABIRE", "name"=>"NABIRE"]);
        City::create(["id"=>"9408", "province_id"=>"94", "city_code"=> "9408", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEPULAUAN YAPEN", "name"=>"KEPULAUAN YAPEN"]);
        City::create(["id"=>"9409", "province_id"=>"94", "city_code"=> "9409", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BIAK NUMFOR", "name"=>"BIAK NUMFOR"]);
        City::create(["id"=>"9410", "province_id"=>"94", "city_code"=> "9410", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PANIAI", "name"=>"PANIAI"]);
        City::create(["id"=>"9411", "province_id"=>"94", "city_code"=> "9411", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PUNCAK JAYA", "name"=>"PUNCAK JAYA"]);
        City::create(["id"=>"9412", "province_id"=>"94", "city_code"=> "9412", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MIMIKA", "name"=>"MIMIKA"]);
        City::create(["id"=>"9413", "province_id"=>"94", "city_code"=> "9413", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN BOVEN DIGOEL", "name"=>"BOVEN DIGOEL"]);
        City::create(["id"=>"9414", "province_id"=>"94", "city_code"=> "9414", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAPPI", "name"=>"MAPPI"]);
        City::create(["id"=>"9415", "province_id"=>"94", "city_code"=> "9415", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN ASMAT", "name"=>"ASMAT"]);
        City::create(["id"=>"9416", "province_id"=>"94", "city_code"=> "9416", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN YAHUKIMO", "name"=>"YAHUKIMO"]);
        City::create(["id"=>"9417", "province_id"=>"94", "city_code"=> "9417", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PEGUNUNGAN BINTANG", "name"=>"PEGUNUNGAN BINTANG"]);
        City::create(["id"=>"9418", "province_id"=>"94", "city_code"=> "9418", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN TOLIKARA", "name"=>"TOLIKARA"]);
        City::create(["id"=>"9419", "province_id"=>"94", "city_code"=> "9419", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SARMI", "name"=>"SARMI"]);
        City::create(["id"=>"9420", "province_id"=>"94", "city_code"=> "9420", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN KEEROM", "name"=>"KEEROM"]);
        City::create(["id"=>"9426", "province_id"=>"94", "city_code"=> "9426", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN WAROPEN", "name"=>"WAROPEN"]);
        City::create(["id"=>"9427", "province_id"=>"94", "city_code"=> "9427", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN SUPIORI", "name"=>"SUPIORI"]);
        City::create(["id"=>"9428", "province_id"=>"94", "city_code"=> "9428", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAMBERAMO RAYA", "name"=>"MAMBERAMO RAYA"]);
        City::create(["id"=>"9429", "province_id"=>"94", "city_code"=> "9429", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN NDUGA", "name"=>"NDUGA"]);
        City::create(["id"=>"9430", "province_id"=>"94", "city_code"=> "9430", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN LANNY JAYA", "name"=>"LANNY JAYA"]);
        City::create(["id"=>"9431", "province_id"=>"94", "city_code"=> "9431", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN MAMBERAMO TENGAH", "name"=>"MAMBERAMO TENGAH"]);
        City::create(["id"=>"9432", "province_id"=>"94", "city_code"=> "9432", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN YALIMO", "name"=>"YALIMO"]);
        City::create(["id"=>"9433", "province_id"=>"94", "city_code"=> "9433", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN PUNCAK", "name"=>"PUNCAK"]);
        City::create(["id"=>"9434", "province_id"=>"94", "city_code"=> "9434", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DOGIYAI", "name"=>"DOGIYAI"]);
        City::create(["id"=>"9435", "province_id"=>"94", "city_code"=> "9435", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN INTAN JAYA", "name"=>"INTAN JAYA"]);
        City::create(["id"=>"9436", "province_id"=>"94", "city_code"=> "9436", "jenis" => "KABUPATEN", "name_lengkap" => "KABUPATEN DEIYAI", "name"=>"DEIYAI"]);
        City::create(["id"=>"9471", "province_id"=>"94", "city_code"=> "9471", "jenis" => "KOTA", "name_lengkap" => "KOTA JAYAPURA", "name"=>"JAYAPURA"]);

    }
}
